module.exports = {
  jmsSidebar: [{ type: "autogenerated", dirName: "journal-management-system" }],
  jobNestSidebar: [{ type: "autogenerated", dirName: "job-nest" }],
  streamspaceSidebar: [{ type: "autogenerated", dirName: "stream-space" }],
};
